global without sharing class WP_DataWrapper
{

   
    public String teamMemberFirst { get;  set; }
    public String teamMemberLast { get;  set; }
    public String teamMemberEmail { get;  set; }
    public String teamMemberTitle  { get;  set; }
    
    public String teamMemberBadgeFirst { get;  set; }
    public String teamMemberBadgeLast { get;  set; }
    public String teamMemberBadgeName { get;  set; }
    
    public String teamMemberAssistantFirst { get;  set; }
    public String teamMemberAssistantLast { get;  set; }
    public String teamMemberAssistantPhone { get;  set; }
    public String teamMemberAssistantEmail  { get;  set; }
                         


}